# Generated by Django 5.2 on 2025-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
